r"""
Assembles paper/main.tex: one self-contained file to paste into Overleaf.

Pulls the abstract, keywords and AI statement out of front_matter.tex, the
Introduction through Literature Review out of paper_draft_sections.tex, and
Methodology through Future Work out of paper_body.tex.

Deliberately drops front_matter.tex's Contributions list: the Introduction
already ends with one, and pasting both duplicates it.

Rerun after merge_paper.py to pick up new numbers.
"""
import re
from pathlib import Path

D = Path(".")
OUT = D / "paper/main.tex"


def read(p):
    return (D / p).read_text(encoding="utf-8")


def strip_comments(t):
    """Drop whole-line % comments but keep escaped \\% inside text."""
    return "\n".join(l for l in t.split("\n")
                     if not l.lstrip().startswith("%"))


def between(t, start, end=None):
    a = t.index(start)
    b = t.index(end, a) if end else len(t)
    return t[a:b].rstrip()


fm = read("paper/front_matter.tex")
abstract = between(fm, r"\begin{abstract}", r"\end{abstract}") + "\n\\end{abstract}"
keywords = between(fm, r"\vspace{0.5em}", "% IEEE template:").rstrip()
ai_stmt = strip_comments(between(fm, r"\section*{Statement on AI Assistance}"))

sections = strip_comments(between(read("paper_draft_sections.tex"),
                                  r"\section{Introduction}"))
body = strip_comments(between(read("paper/paper_body.tex"),
                              r"\section{Methodology}"))

PREAMBLE = r"""% =====================================================================
% Disentangling Scale from Targeted Pretraining Depth
% CSE791 Group 11
%
% ONE self-contained file. Paste the whole thing into Overleaf's main.tex.
%
% UPLOAD THESE FOUR IMAGES into a folder in the project (any of the names
% listed in \graphicspath below will be found):
%     fig_method.png  fig_scale.png  fig_beforeafter.png  fig_difficulty.png
%
% AND upload your references.bib. It must contain the 11 keys listed at the
% bottom of this file under "BIBLIOGRAPHY", plus the entries in
% new_references.bib.
%
% SINGLE COLUMN instead? Change the documentclass line to drop "twocolumn",
% then change the one "figure*" environment (around fig_method.png) to
% "figure" and its \textwidth to \linewidth.
%
% Generated by build_main.py. Rerun that after merge_paper.py.
% =====================================================================
\documentclass[10pt,twocolumn,letterpaper]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[letterpaper,margin=0.75in]{geometry}

\usepackage{graphicx}
\graphicspath{{figures/}{figs/}{figured/}{./}}

\usepackage{amsmath}          % \text, \alpha, \sim
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{url}
\usepackage[hidelinks]{hyperref}

% \parencite and \textcite come from biblatex. If your template uses plain
% BibTeX instead, delete these two lines, add \usepackage{natbib}, and
% replace \parencite -> \citep and \textcite -> \citet throughout.
\usepackage[backend=biber,style=numeric,sorting=none]{biblatex}
\addbibresource{references.bib}

\title{\bfseries Disentangling Scale from Targeted Pretraining Depth:\\
Testing the Less-Is-More Hypothesis for\\
Bengali Mathematical Reasoning}

% TODO: fill in the full author list and affiliations for your group.
\author{Monowar Zamil Abir\\
Department of Computer Science and Engineering\\
BRAC University\\
\texttt{zamilabir24@gmail.com}}

\date{}

\begin{document}
\maketitle
"""

parts = [
    PREAMBLE,
    "",
    abstract,
    "",
    keywords,
    "",
    sections,
    "",
    body,
    "",
    ai_stmt,
    "",
    r"""% =====================================================================
% BIBLIOGRAPHY
%
% Keys cited by this document. Everything except the first group should
% already be in your references.bib from the original draft; the rest are
% in new_references.bib and need appending.
%
% already yours : ahmed2025bennumeval, alnazi2025eval, muennighoff2025s1,
%                 nahin2025titullm, paul2025somadhan, qi2025xreasoning,
%                 raihan2025tigerllm, sobhani2026mathmist, xia2024less,
%                 ye2025limo, yong2025crosslingual
% from new_references.bib : ganitllm, kaplan2020scaling, wei2022emergent,
%                 hu2021lora, biderman2024lora, ahia2023alllanguages,
%                 petrov2023language, zhou2023lima, llama3herd, gemma3, qwen3
%
% VERIFY the ganitllm entry's author list and the three arXiv ids marked
% VERIFY in new_references.bib before submitting.
% =====================================================================
\printbibliography

\end{document}""",
]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(parts), encoding="utf-8")

t = OUT.read_text(encoding="utf-8")
prose = "\n".join(l for l in t.split("\n") if not l.lstrip().startswith("%"))
print("wrote", OUT)
print("  lines            :", len(t.split("\n")))
print("  words (no comments): ~%d" % len(prose.split()))
print("  sections         :", len(re.findall(r"\n\\section\{", t)))
print("  subsections      :", len(re.findall(r"\n\\subsection\{", t)))
print("  figures          :", t.count(r"\includegraphics"))
print("  tables           :", len(re.findall(r"\\begin\{table\}", t)))
print("  contributions    :", t.count("Our contributions are:"), "(must be 1)")
print("  \\NUM / \\TODO      :", t.count(r"\NUM{") + t.count(r"\TODO{"))
print("  em dashes        :", sum(t.count(c) for c in "\u2014\u2013"))
print("  non-ascii        :", sorted({c for c in t if ord(c) > 127}) or "none")

labels = set(re.findall(r"\\label\{([^}]+)\}", t))
refs = set(re.findall(r"\\(?:ref|autoref)\{([^}]+)\}", t))
print("  dangling refs    :", sorted(refs - labels) or "none")
