r"""
Builds paper/paper_body.tex: one file to paste into Overleaf.

paper_draft_methods_results.tex still carries the ORIGINAL Results section,
written before any evaluation finished, with 53 \NUM{} and 4 \TODO{}
placeholders. paper/results_draft.tex is the replacement, with real numbers.
Pasting both would give you two Results sections. This script drops the old
one, splices in the new one, and fills the three placeholders that live
outside Results.
"""
from pathlib import Path

SRC = Path("paper_draft_methods_results.tex")
RES = Path("paper/results_draft.tex")
OUT = Path("paper/paper_body.tex")

# Generated by paper_stats.py and measure_tokenizer.py. Inlined here so
# paper_body.tex pastes as one file with no \\input to resolve.
ADHERENCE_TABLE = Path("paper/tab_adherence.tex").read_text(encoding="utf-8").rstrip()
TOKENIZER_TABLE = Path("paper/tab_tokenizer.tex").read_text(encoding="utf-8").rstrip()

lines = SRC.read_text(encoding="utf-8").split("\n")


def line_of(prefix, start=0):
    for i in range(start, len(lines)):
        if lines[i].startswith(prefix):
            return i
    raise SystemExit("could not find " + prefix)


i_meth = line_of(r"\section{Methodology}")
i_res = line_of(r"\section{Results}")
i_disc = line_of(r"\section{Discussion}")

methodology = lines[i_meth:i_res]
tail = lines[i_disc:]

# new Results: everything from its \section line down, header comment dropped
res = RES.read_text(encoding="utf-8").split("\n")
res = res[next(k for k, l in enumerate(res) if l.startswith(r"\section{Results}")):]

# ---- fill the placeholders that survive outside the Results section ----
tail = "\n".join(tail)

tail = tail.replace(
    r"accuracy of \NUM{acc} shows real latent capability, and elicitation still"
    "\nproduced nothing.",
    "accuracy of 44.8\\% shows real latent capability, and elicitation still\n"
    "produced nothing.")

tail = tail.replace(
    r"made models less Bengali. \TODO{Confirm count and magnitudes at final n.}",
    "made models less Bengali. Six of the seven backbones produced a lower\n"
    "proportion of Bengali characters after fine-tuning than before it. The\n"
    "decline was sharpest in exactly the models that started most Bengali:\n"
    "TituLLM-3B-Instruct fell from 97.9\\% to 80.8\\% and TituLLM-1B-Instruct from\n"
    "98.3\\% to 81.3\\%. TigerLLM-1B fell from 87.0\\% to 82.7\\% and Qwen3-1.7B from\n"
    "89.3\\% to 84.1\\%. Qwen3-0.6B was the single exception, rising slightly from\n"
    "85.6\\% to 87.8\\%. Training on Bengali reasoning traces made most of these\n"
    "models write less Bengali, not more.\n\n"
    "Table~\\ref{tab:adherence} reports the paired differences with their\n"
    "95\\% confidence intervals. In all six declining models the interval\n"
    "excludes zero. Qwen3-0.6B is the exception in both directions: its mean\n"
    "rose by 2.1 points but the interval spans zero ($-1.2$ to $+5.4$), so we\n"
    "do not claim it improved, even though more of its individual items fell\n"
    "than rose.\n\n"
    + ADHERENCE_TABLE)

tail = tail.replace(
    r"\textbf{Sample size is not uniform.} \TODO{State final per-model n and note"
    "\nwhere intervals differ.}",
    "\\textbf{Sample size is not uniform.} Six of the seven backbones are\n"
    "evaluated on the full 250 held-out items. TituLLM-1B base is evaluated on\n"
    "100, because it was dropped from the extension after producing degenerate\n"
    "output at 0 to 2\\% accuracy across its first hundred items. Every\n"
    "comparison is paired on the items a model completed in both conditions, so\n"
    "no accuracy is computed across mismatched item sets, but the Wilson\n"
    "interval on that one row is correspondingly wider and should not be read\n"
    "as tightly as the others.")

tail = tail.replace(
    r"Scale predicts performance. \TODO{One sentence with the final scale-ladder"
    "\nfigures and p-values.} Targeted Bengali pretraining does not: a",
    "Scale predicts performance: within a single model family holding\n"
    "pretraining constant, accuracy rose from 3.6\\% at 0.6B to 16.8\\% at 1.7B to\n"
    "44.8\\% at 4B. Targeted Bengali pretraining does not: a")

body = [
    "% =====================================================================",
    "% PAPER BODY: Methodology through Future Work.",
    "%",
    "% Generated by merge_paper.py. Do not edit both this file and",
    "% paper_draft_methods_results.tex; this one supersedes it. The old",
    "% Results section has been replaced with the real numbers.",
    "%",
    "% PREAMBLE (add before \\begin{document}):",
    "%   \\usepackage{graphicx}",
    "%   \\graphicspath{{figures/}{figs/}{figured/}{./}}",
    "%",
    "% FIGURES to upload: fig_method.png, fig_scale.png,",
    "%                    fig_beforeafter.png, fig_difficulty.png",
    "%",
    "% If your paper is SINGLE-column, change the figure* environment around",
    "% fig_method.png to figure, and \\textwidth to \\linewidth.",
    "% =====================================================================",
    "",
]
body += methodology + [""] + res + [""] + tail.split("\n")

OUT.write_text("\n".join(body), encoding="utf-8")

text = "\n".join(body)
print("wrote", OUT)
print("  lines        :", len(body))
print("  words        : ~%d" % len([w for w in text.split() if not w.startswith("%")]))
print("  \\NUM{} left  :", text.count(r"\NUM{"))
print("  \\TODO{} left :", text.count(r"\TODO{"))
print("  figures      :", text.count(r"\includegraphics"))
print("  em dashes    :", sum(text.count(c) for c in "\u2014\u2013"))
print("  non-ascii    :", sorted({c for c in text if ord(c) > 127}) or "none")


# ---- restore the tokenizer table, which lived in the deleted Results ----
TOKTAB = TOKENIZER_TABLE + "\n"

txt = OUT.read_text(encoding="utf-8")
anchor = ("Table~" + chr(92) + "ref{tab:tokenizer} reports token counts for the "
          "same 873 training\ntraces under each tokenizer.\n")
assert anchor in txt, "tokenizer anchor moved"
txt = txt.replace(anchor, anchor + "\n" + TOKTAB)

# and give the difficulty figure the cross-reference it was missing
old = ("We tested this directly. Holding the backbone, the LoRA configuration, "
       "the seed,")
new = ("Figure~" + chr(92) + "ref{fig:difficulty} reports that test. Holding the "
       "backbone, the\nLoRA configuration, the seed,")
txt = txt.replace(old, new, 1)

OUT.write_text(txt, encoding="utf-8")
print("\nrestored tab:tokenizer and linked fig:difficulty")
